"""add user pin_hash

Revision ID: a210df2a0774
Revises: a38bfcde4564
Create Date: 2026-07-01 16:05:31.536656
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a210df2a0774'
down_revision: str | None = 'a38bfcde4564'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pin_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pin_hash')
    # ### end Alembic commands ###
