"""add bank connections

Revision ID: b4b8c9070e5c
Revises: 6c42302253f3
Create Date: 2026-07-01 21:33:32.705999
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4b8c9070e5c'
down_revision: str | None = '6c42302253f3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_connections',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('aspsp_name', sa.String(length=120), nullable=False),
    sa.Column('aspsp_country', sa.String(length=8), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('encrypted_session_id', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_connections_state'), 'bank_connections', ['state'], unique=True)
    op.create_index(op.f('ix_bank_connections_user_id'), 'bank_connections', ['user_id'], unique=False)
    op.create_table('bank_account_links',
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('encrypted_external_uid', sa.String(length=512), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('identifier_masked', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['connection_id'], ['bank_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_account_links_account_id'), 'bank_account_links', ['account_id'], unique=False)
    op.create_index(op.f('ix_bank_account_links_connection_id'), 'bank_account_links', ['connection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_account_links_connection_id'), table_name='bank_account_links')
    op.drop_index(op.f('ix_bank_account_links_account_id'), table_name='bank_account_links')
    op.drop_table('bank_account_links')
    op.drop_index(op.f('ix_bank_connections_user_id'), table_name='bank_connections')
    op.drop_index(op.f('ix_bank_connections_state'), table_name='bank_connections')
    op.drop_table('bank_connections')
    # ### end Alembic commands ###
